recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   db:
      driver :  com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.68:3306/tx?useUnicode=true&amp;characterEncoding=utf8
      username: xiaoyu
      password: Wgj@555888
