recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   mongo :
      url : 192.168.1.68:27017
      dbName : happylife
      userName : xiaoyu
      password : 123456
